runtime: nodejs16

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /data
  static_dir: data
  expiration: '1m'

- url: /about/
  static_files: about/index.html
  upload: about/index.html

- url: /directory/
  static_files: directory/index.html
  upload: directory/index.html
